// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-W8fq4xpOcdhWMBERyJeAB5t0si2q_Rc',
    appId: '1:156958157676:web:3af39af4837a05f9472149',
    messagingSenderId: '156958157676',
    projectId: 'trigram-6d951',
    authDomain: 'trigram-6d951.firebaseapp.com',
    storageBucket: 'trigram-6d951.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGxEzWmD_AXadrXxkiDQRwLM70E4xIdsk',
    appId: '1:156958157676:android:4a9069abecbc8343472149',
    messagingSenderId: '156958157676',
    projectId: 'trigram-6d951',
    storageBucket: 'trigram-6d951.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-W8fq4xpOcdhWMBERyJeAB5t0si2q_Rc',
    appId: '1:156958157676:web:cc18e9a0b0d11ff1472149',
    messagingSenderId: '156958157676',
    projectId: 'trigram-6d951',
    authDomain: 'trigram-6d951.firebaseapp.com',
    storageBucket: 'trigram-6d951.firebasestorage.app',
  );
}
